version: '3.7'

services:
  web:
    build: ./app
    command: sh on-container-start.sh
    volumes:
      - ./app:/app
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    # env_file: .env
    environment:
      - DEBUG=1
      - SECRET_KEY=foo

  nginx:
    build: ./nginx
    # depends_on:
    #   - web
    # command: nginx -g 'daemon off;'
    volumes:
      - ./app/staticfiles:/usr/src/app/staticfiles
      - ./app/mediafiles:/usr/src/app/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - web
