version: '3.7'

services:
  web:
    build: ./app
    command: sh on-container-start.sh
    volumes:
      - ./app:/app
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    # env_file: .env
    # environment:
      # CACHE_IMAGE: mjhea0/docker-ci-cache
    environment:
      DEBUG: 1
      SECRET_KEY: "g!@a2x+)1y$w_zo7q(vei!q90-tk_$si97%zfx%r^5_sw1o%sg"

  nginx:
    build: ./nginx
    # depends_on:
    #   - web
    # command: nginx -g 'daemon off;'
    volumes:
      - ./app/static:/usr/src/app/staticfiles
      - ./app/mediafiles:/usr/src/app/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - web
